server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9099
logging:
  file:
    max-size: 50MB
  level:
    root: info
    web: info
  path: logs
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] [%c:%M:%L] [%p] - %m%n"
logging.file: /home/${logging.path}/blog.log
spring:
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
qiniu:
  accessKey: nS-F8PFet2_ZjEJnS1OJE4O8LsmEZifTgCz0fhen
  secretKey: cGBXZRe5oK5bL5Sg5ZCAalaDhQhjJeGjb34qG3eP
  bucket: myblog
  prefix: pqieq9o0q.bkt.clouddn.com