server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9099

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
qiniu:
  accessKey: nS-F8PFet2_ZjEJnS1OJE4O8LsmEZifTgCz0fhen
  secretKey: cGBXZRe5oK5bL5Sg5ZCAalaDhQhjJeGjb34qG3eP
  bucket: myblog
  prefix: file